In [1]:
print("hello")

hello


# numpy

In [2]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3],                
                [4, 5, 6]])
print("2D Array:\n", arr2)

# 배열의 형태 변경
# shape() 모양(행, 열)
# arr_reshaped = arr2.reshape(3, 2)   # (3행, 2열)로 구조가 바뀜
arr_reshaped = arr2.reshape(6, -1)   # (3행, 2열)로 구조가 바뀜

print("Reshaped Array:\n", arr_reshaped)
# 행과 열이 가능형태로 변환해야 함 ex reshape(3,4)는 에러
# reshape(3, -1) -는 앞에 계산해서 자동으로 행열을 만듬
# reshape(-1)은 한줄 1차원으로 바꿔줌 하지만 (-1,-1)은 에러
# reshape(1,3,-2)는 3차원 

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Reshaped Array:
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
# 중급: 배열 연산 및 함수
import numpy as np

# 배열 덧셈
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Array Addition:", arr1 + arr2)

# 배열 곱셈
print("Array Multiplication:", arr1 * arr2)

# 통계 함수 사용
arr = np.array([1, 2, 3, 4, 5])
print("Mean:", np.mean(arr))    # mean() 평균
print("Standard Deviation:", np.std(arr))   # std() 표준편차

Array Addition: [5 7 9]
Array Multiplication: [ 4 10 18]
Mean: 3.0
Standard Deviation: 1.4142135623730951


In [5]:
nums = [i for i in range(100000000)]

In [9]:
%%time
# 평균
list_mean = sum(nums)/len(nums)

CPU times: total: 6.12 s
Wall time: 6.41 s


In [8]:
tmp = np.array(nums)

In [10]:
%%time 
# numpy mean 속도가 훨씬 빠르다 
np_mean = np.mean(tmp)

CPU times: total: 156 ms
Wall time: 157 ms


In [11]:
# 브로드 캐스팅 원하던 모양을 맞춰주는게 브로드캐스팅
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [12]:
arr + 1

array([2, 3, 4])

In [13]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [15]:
arr + np.array([11,12,13])

array([[12, 14, 16],
       [15, 17, 19]])

In [17]:
import numpy as np

# 브로드캐스팅
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Broadcasting Addition:\n", arr + 1)

# 선형 대수: 행렬 곱셈
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print("Matrix Multiplication:\n", np.dot(a, b)) # dot()행렬곱셈

Broadcasting Addition:
 [[2 3 4]
 [5 6 7]]
Matrix Multiplication:
 [[19 22]
 [43 50]]


In [19]:
np.int_ # int8(0~255), int16(2**16),... int256 해당자료형이가지는 비트수 
np.float_ # float16(),... float256 메모리를 차지하는 공간이 많으면 느리다 -> 최적화 필요

numpy.float64

In [22]:
import numpy as np
float

float

In [23]:
from PIL import Image

# 열기
image = Image.open('img.png')

In [24]:
image.save("output.jpg")

In [25]:
# 이미지 회전
rotated_image = image.rotate(180)
rotated_image.save("rotated.jpg")

In [27]:
bw_image = image.convert("L")
bw_image.save("gray.jpg")

In [29]:
cropped_image = image.crop(100, 100, 400, 400)
cropped_image.save("cropped.jpg")

TypeError: Image.crop() takes from 1 to 2 positional arguments but 5 were given

In [40]:
from PIL import Image, ImageDraw, ImageFont

# 이미지 열기
img1 = Image.open("img1.jpg")
draw = ImageDraw.Draw(img1)
# 사용할 폰트 정의
#font = ImageFont.truetype("arial.ttf", size=45)
# 기본 폰트 사용
font = ImageFont.load_default()
# 이미지에 텍스트 추가 (x, y, message, fill=color, font=font)
draw.text((10, 10), "Python Backend!", fill="white", font=font)
# 텍스트가 추가된 이미지 저장
img1.save("text_added.jpg")

In [37]:
draw = ImageDraw.Draw(img1)

AttributeError: 'str' object has no attribute 'load'

In [32]:
font = ImageFont.load_default()

In [33]:
draw.text((10, 10), "Python Backend", fill="red", font=font)
image_new.save("text_added.jpg")

NameError: name 'image_new' is not defined

In [41]:
# 예제 6: 이미지 필터 적용
from PIL import Image, ImageFilter

# 이미지 열기
image = Image.open("img.png")
# 이미지에 가우시안 블러 필터 적용
blurred_image = image.filter(ImageFilter.GaussianBlur(5)) # 가우시안 블러 숫자로 블러가 진해짐
blurred_image.save("blurred.jpg")

In [3]:
# 예제 7: 배치 이미지 사이즈 조정
import os
from PIL import Image

input_folder = 'input_images/'
output_folder = 'output_images/'

# 입력 폴더 내의 모든 이미지 파일에 대해 반복
for filename in os.listdir(input_folder):   # 인풋폴더 리스트화
    if filename.endswith(".jpg"):
        img_path = os.path.join(input_folder, filename) # 이미지경로 .jpg파일이있는
        img = Image.open(img_path)  # img_path경로를 열어서
        # 이미지 사이즈 조정
        resized_img = img.resize((128, 128)) 
        # 조정된 이미지 저장
        resized_img.save(os.path.join(output_folder, filename))

FileNotFoundError: [Errno 2] No such file or directory: 'output_images/gray.jpg'

In [4]:
from PIL import Image, ImageEnhance

# 이미지 열기
image = Image.open("img.png")
# 대비 조정 객체 생성
enhancer = ImageEnhance.Contrast(image)
# 대비를 2로 증가
enhanced_image = enhancer.enhance(2)
# 대비가 증가된 이미지 저장
enhanced_image.save("enhanced_contrast.jpg")

In [5]:
from PIL import Image

# 이미지 열기
image = Image.open("img.png")
# 이미지 저장
image.save("output.jpg")

In [6]:
from PIL import Image
from collections import Counter

# 이미지 열기
image = Image.open("img.png")
# 이미지의 모든 픽셀 값 가져오기
pixels = list(image.getdata())
# 가장 흔한 색상 10개 찾기
most_common_colors = Counter(pixels).most_common(10)

print(most_common_colors)

[((21, 53, 126), 43205), ((240, 232, 213), 22200), ((240, 231, 214), 6439), ((240, 232, 211), 6012), ((21, 53, 128), 4937), ((239, 232, 213), 4669), ((242, 231, 213), 4623), ((21, 54, 125), 4351), ((242, 230, 214), 3822), ((239, 233, 211), 3631)]


In [10]:
import numpy as np
np.array(image).shape

(640, 640, 3)

In [16]:
array = np.random.randint(0, 255, size=(440,630, 3), dtype=np.uint8)
array

array([[[182, 197, 169],
        [ 76,  63,  97],
        [208, 184, 127],
        ...,
        [111, 151, 184],
        [ 44, 168,  71],
        [108, 238,   9]],

       [[214, 247, 109],
        [  5, 170, 135],
        [ 89, 186, 183],
        ...,
        [ 51, 150,  98],
        [162, 219, 101],
        [ 66, 171, 104]],

       [[195,  73, 242],
        [153, 142,  98],
        [ 53, 212, 199],
        ...,
        [109, 234, 191],
        [  3, 204, 231],
        [160,  73, 127]],

       ...,

       [[234,  49, 214],
        [152, 249, 254],
        [122,  22, 189],
        ...,
        [231,  36, 149],
        [ 89, 153, 253],
        [133,  53, 116]],

       [[ 44, 229,  15],
        [172,  37,  82],
        [245, 115, 178],
        ...,
        [149,   5,  60],
        [100,  70, 197],
        [189, 102,  49]],

       [[148,  77, 219],
        [131,  46, 218],
        [ 58,  67,  17],
        ...,
        [ 54, 176, 100],
        [224, 212,  37],
        [250, 238, 160]]

In [14]:
array.dtype

dtype('int32')

# OpenCv

In [9]:
# 이미지 읽기, 표시, 저장
import cv2

# 이미지 읽기
img = cv2.imread('img.png')
# 이미지 표시
cv2.imshow('Image', img)
cv2.waitKey(0)  # Key입력을 기다리는데 0이면 영원히 기다림 # 밀리초
cv2.destroyAllWindows() # 화면을 닫기 위해 필수
# 이미지 저장
cv2.imwrite('output.jpg', img)

True

In [12]:
# 이미지 그레이스케일 변환
# 산업쪽에서 상처나 흔적 등 확인하려고  그레이스케일을 많이 씀
import cv2

# 이미지 읽기
img = cv2.imread('img.png')
# 그레이스케일 변환
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) # RGB의 순서가 BGR로 씀 
# 변환된 이미지 표시
cv2.imshow('Grayscale Image', gray_img)
cv2.imshow('Original Image', img)   # 오리지널 이미지
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
# 이미지 회전
import cv2

# 이미지 읽기
img = cv2.imread('img.png')
# 이미지 중심을 기준으로 90도 회전
height, width = img.shape[:2]
center = (width / 2, height / 2)
rotate_matrix = cv2.getRotationMatrix2D(center=center, angle=90, scale=1) # 선형대수 관련된 변환 행열을 만들고 
rotated_img = cv2.warpAffine(src=img, M=rotate_matrix, dsize=(width, height)) # dsize 결과이미지크기
# 회전된 이미지 표시
cv2.imshow('Rotated Image', rotated_img)
cv2.imshow('Original Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [25]:
# 가우시안 블러 적용
import cv2

# 이미지 읽기
img = cv2.imread('img.png')
# 가우시안 블러 적용
blurred_img = cv2.GaussianBlur(img, (5, 5), 0)
# 블러된 이미지 표시
cv2.imshow('Blurred Image', blurred_img)
cv2.imshow('Original Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [26]:
# 경계 감지 (Canny Edge Detection)
import cv2

# 이미지 읽기
img = cv2.imread('img.png')
# 그레이스케일 변환
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
# Canny edge detection 적용
edges = cv2.Canny(image=gray_img, threshold1=100, threshold2=200)
# 경계가 감지된 이미지 표시
cv2.imshow('Edge Detected Image', edges)
cv2.imshow('Original Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
import cv2

# 얼굴 감지를 위한 분류기 로드
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

# 이미지 읽기
img = cv2.imread('input.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# 얼굴 감지
faces = face_cascade.detectMultiScale(gray, 1.1, 4)

# 감지된 얼굴 주위에 사각형 그리기
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# 결과 이미지 표시
cv2.imshow('Face Detected', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

error: OpenCV(4.9.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.cpp:196: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


In [16]:
# 동영상 처리
import cv2

# 동영상 파일 열기
cap = cv2.VideoCapture('video.mp4')

# 출력 파일 설정
fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # 출력 파일의 코덱 설정
out = cv2.VideoWriter('video.mp4', fourcc, 20.0, (640, 480), isColor=False)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # 프레임을 그레이스케일로 변환
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # 변환된 프레임을 출력 파일에 쓰기
    out.write(gray)

    # 변환된 프레임을 화면에 표시
    cv2.imshow('frame', gray)
    if cv2.waitKey(1) == ord('q'):
        break

# 작업 완료 후 해제
cap.release()
out.release()
cv2.destroyAllWindows()

In [1]:
# 동영상 처리
import cv2

# 동영상 파일 열기
cap = cv2.VideoCapture('video.mp4')
    # 0 컴퓨터카메라 웹캠
    # 1 다른 카메라 
    # 2 다른 새로운 카메라

# 출력 파일 설정
# fourcc = cv2.VideoWriter_fourcc(*'MP4V')  # 출력 파일의 코덱 설정
# out = cv2.VideoWriter('video.mp4', fourcc, 20.0, (640, 480), isColor=False)
img_bool = True

while cap.isOpened():
    ret, frame = cap.read() # 1장 보내고
    
    if not ret: 
        break
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    edges = cv2.Canny(image=gray, threshold1=100, threshold2=200)

    # cv2.imshow('frame', frame)  # 바로보여줌
    # cv2.imshow('frame', edges)  # 바로보여줌
    if cv2.waitKey(1) == ord('q'):      #  or cv2.waitKey(1) == ord('a')
        break
    # else:
    #     img_bool = ~img_bool

    # if img_bool:
    #     cv2.imshow('frame', gray)
    # else:
    cv2.imshow('frame',edges)


cap.release()       # 외부리소스 읽으면 반환
out.release()       # 꼭 써야함 
cv2.destroyAllWindow()  

NameError: name 'out' is not defined

: 

In [1]:
import cv2
import mediapipe as mp

mp_pose = mp.solutions.pose
pose = mp_pose.Pose(static_image_mode=False, model_complexity=1, smooth_landmarks=True, min_detection_confidence=0.5, min_tracking_confidence=0.5)
mp_drawing = mp.solutions.drawing_utils

cap = cv2.VideoCapture('video.mp4')
img_bool = True
while cap.isOpened():
    ret, frame = cap.read()

    if not ret:
        break

    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = pose.process(frame_rgb)

    if results.pose_landmarks:
        mp_drawing.draw_landmarks(frame, results.pose_landmarks, mp_pose.POSE_CONNECTIONS,
                                mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=2),
                                mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2))


    if cv2.waitKey(1) == ord('q'):
        break

    cv2.imshow('frame', frame)

cap.release()
cv2.destroyAllWindows()